language: java
sudo: 'required'
services:
  - 'docker'
node_js:
  - '10.16.1'
before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - set -e
  - mvn clean install
  - yarn install --frozen-lockfile --ignore-scripts
  - yarn test
  - yarn build
  - set +e
branches:
  only:
    - master
    - docker
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: target/storybook/
    target-branch: gh-pages
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./dockerDeploy.sh
    on:
      branch: docker
