language: java
node_js:
  - '10.16.1'
cache: yarn
before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - mvn clean install
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/storybook/
  target-branch: gh-pages
  on:
    branch: master
