language: java
sudo: 'required'
services:
  - 'docker'
node_js:
  - '10.16.1'
cache: yarn
before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - 'sudo ./.travis/main.sh'
script:
  - set -e
  - mvn clean install
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build
  - set +e
  - 'make image'
branches:
  only:
  - master
  - docker-aws
after_success:
  - if [[ "$TRAVIS_BRANCH" == "docker-aws" ]]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      make push-image ;
    fi
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: target/storybook/
  target-branch: gh-pages
  on:
    branch: master
  # Setup registry deployment
  provider: script
  script: bash scripts/deploy.sh 
  on:
    branch: docker-aws
